spring:
  application:
    name: gestion-personas
  datasource:
    url: jdbc:postgresql://localhost:5432/ssoma_db
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd
  # Configuración para subida de archivos
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

server:
  port: 8083

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

logging:
  level:
    com.ssoma: DEBUG
    org.springdoc: DEBUG

app:
  upload:
    dir: uploads